import streamlit as st

from backend.LLM.ollama_chat import chat_with_advisor, summarize_conversation
from backend.LLM.chat_store import (
    load_chat_history,
    save_message,
    clear_chat_history,
)


def render_chat_page(user, ticker, action_text, conf_pct, risk_label, explanation):
    st.subheader("💬 Chat with the Advisor")

    st.info(
        "This is an **educational prototype**, not financial advice.\n\n"
        "- It explains how the demo model is thinking about a stock.\n"
        "- It cannot consider your full financial situation.\n"
        "- Do not make real trading decisions based on this tool."
    )

    with st.expander("What this chat can and cannot do"):
        st.markdown(
            """
            **✅ This chat can help you:**
            - Understand why the model suggests BUY / SELL / HOLD.
            - Interpret technical indicators and risk levels.
            - Learn basic investing and risk management concepts.
            - Understand limitations of the RL model and backtests.

            **🚫 This chat cannot do:**
            - Give personalised financial advice.
            - Guarantee profits or predict the future with certainty.
            - Replace professional financial advice.
            """
        )

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Current ticker", ticker)
    with col2:
        st.metric("Model action", action_text)
    with col3:
        st.metric("Signal confidence", f"{conf_pct}%")

    st.caption(
        f"Risk level for {ticker}: **{risk_label}**. Responses are generated by a local language model and are for educational purposes only."
    )

    st.divider()

    chat_history = load_chat_history(user_id=user.id, ticker=ticker, limit=50)

    if len(chat_history) >= 8:
        if st.button("🧾 Summarise conversation so far"):
            convo_text_for_summary = ""
            for m in chat_history:
                speaker = "User" if m["role"] == "user" else "Advisor"
                convo_text_for_summary += f"{speaker}: {m['content']}\n"

            with st.spinner("Summarising conversation..."):
                try:
                    summary = summarize_conversation(
                        ticker=ticker,
                        conversation_history=convo_text_for_summary,
                    )
                    st.markdown("**Conversation summary so far:**")
                    st.write(summary)
                except Exception:
                    st.warning("Sorry, I couldn't summarise the conversation right now.")

    st.markdown("### Conversation")

    if not chat_history:
        st.write("No questions yet. Try asking: *Why is it suggesting HOLD for this stock?*")
    else:
        for msg in chat_history:
            if msg["role"] == "user":
                col_left, col_right = st.columns([0.7, 0.3])
                with col_left:
                    st.markdown(
                        f"""
                        <div style="background-color:#e8f4ff;padding:8px 12px;border-radius:16px;margin-bottom:6px;">
                            <strong>You:</strong><br>{msg['content']}
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )
            else:
                col_left, col_right = st.columns([0.3, 0.7])
                with col_right:
                    st.markdown(
                        f"""
                        <div style="background-color:#f4f4f4;padding:8px 12px;border-radius:16px;margin-bottom:6px;">
                            <strong>Advisor:</strong><br>{msg['content']}
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

    st.divider()

    pos = explanation.get("top_positive", [])
    neg = explanation.get("top_negative", [])
    pos_features = [item["feature"] for item in pos]
    neg_features = [item["feature"] for item in neg]

    pos_text = ", ".join(pos_features) if pos_features else "no strong positive signals"
    neg_text = ", ".join(neg_features) if neg_features else "no strong negative signals"

    backtest_summary = (
        "Strategy comparison summary for this stock:\n"
        "- RL strategy performance: see the strategy comparison chart.\n"
        "- Buy & Hold baseline: holding the stock over the same period.\n"
        "- RSI strategy: simple technical indicator-based strategy.\n"
        "These are historical tests and do not guarantee future performance."
    )

    rl_confidence = conf_pct / 100.0 if conf_pct is not None else None

    st.markdown("### Quick questions")
    qp_col1, qp_col2 = st.columns(2)
    qp_col3, qp_col4 = st.columns(2)

    quick_question = None
    with qp_col1:
        if st.button("📈 Why is it recommending this?"):
            quick_question = "Why is the model recommending this action for this stock?"
    with qp_col2:
        if st.button("⚠️ What are the risks?"):
            quick_question = "What are the main risks for this stock according to the model?"
    with qp_col3:
        if st.button("📊 How does this compare to Buy & Hold?"):
            quick_question = "How does the RL strategy compare to a simple Buy and Hold strategy on past data?"
    with qp_col4:
        if st.button("🔎 What indicators influenced this?"):
            quick_question = "Which indicators or features most influenced this recommendation?"

    st.markdown("### Ask your own question")
    user_q = st.text_area(
        "Your question",
        placeholder="Ask something about the recommendation, risk, or historical testing...",
        key="advisor_text",
    )

    btn_col1, btn_col2 = st.columns([0.6, 0.4])
    with btn_col1:
        ask_clicked = st.button("Ask the advisor", key="ask_advisor_btn")
    with btn_col2:
        clear_clicked = st.button("🗑️ Clear conversation", key="clear_convo_btn")

    if clear_clicked:
        clear_chat_history(user.id, ticker)
        st.success("Conversation cleared for this stock.")
        st.rerun()

    question_to_send = None
    if quick_question is not None:
        question_to_send = quick_question
    elif ask_clicked and user_q.strip():
        question_to_send = user_q.strip()

    if question_to_send is not None:
        recent_msgs = load_chat_history(user_id=user.id, ticker=ticker, limit=20)
        convo_text = ""
        for m in recent_msgs:
            speaker = "User" if m["role"] == "user" else "Advisor"
            convo_text += f"{speaker}: {m['content']}\n"

        try:
            answer = chat_with_advisor(
                user_question=question_to_send,
                ticker=ticker,
                action_text=action_text,
                pos_text=pos_text,
                neg_text=neg_text,
                backtest_summary=backtest_summary,
                conversation_history=convo_text,
                rl_confidence=rl_confidence,
                risk_label=risk_label,
            )

            save_message(user.id, ticker, "user", question_to_send)
            save_message(user.id, ticker, "assistant", answer)
            st.rerun()

        except Exception as e:
            st.error("Could not reach the local language model.")
            st.caption(str(e))